services:
  - type: web
    name: llbp-generator
    env: node
    plan: free
    buildCommand: |
      cd client && npm install && npm run build
      cd ../server && npm install
    startCommand: node server.js
    buildFilter: "server/**"
    envVars:
        - key: OPENAI_API_KEY
    sync: false
      - key: NODE_VERSION
        value: 18
